fixtures:
  repositories:
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    chocolatey: git://github.com/puppetlabs/puppetlabs-chocolatey.git
    inifile: git://github.com/puppetlabs/puppetlabs-inifile.git
    portage: git://github.com/gentoo/puppet-portage.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: '>= 6.0.0'
